export const words = [
    'Hack Nexus',
    'Ethical Hacking',
    'Penetration Testing',
    'Cybersecurity',
    'Network Security',
    'Vulnerability Assessment',
    'Python',
    'JavaScript',
    'TypeScript',
    'React',
    'Node.js',
    'Linux',
    'Kali Linux',
    'Metasploit',
    'Wireshark',
    'Nmap',
    'Burp Suite',
    'OWASP',
    'SQL Injection',
    'XSS',
    'CSRF',
    'Firewall',
    'Encryption',
    'Decryption',
    'Cryptography',
    'Hash',
    'SSL/TLS',
    'API',
    'REST',
    'GraphQL',
    'Docker',
    'Kubernetes',
    'Git',
    'GitHub',
    'CI/CD',
    'DevOps',
    'Cloud',
    'AWS',
    'Azure',
    'GCP',
    'Malware',
    'Ransomware',
    'Phishing',
    'Social Engineering',
    'Zero Day',
    'Exploit',
    'Payload',
    'Shell',
    'Terminal',
    'CLI',
    'Shell',
    'Bash',
    'Zsh',
    'PowerShell',
    'Vim',
    'SQL'
];
